### PR TITLE
Insane Website Update (:

### PR DESCRIPTION
**Pull request by LiamSirBean**

### CODE REVIEW

**Review by energeticnetwork — COMMENTED** [review]
This does nothing. i would close this if i can he just copyed the code deleted it then pasted it he diddnt do nothing

**Comment by LiamSirBean** [comment]
I accidentally updated that but the other code is changed and very different.

**Comment by LiamSirBean** [comment]
> This does nothing. i would close this if i can he just copyed the code deleted it then pasted it he diddnt do nothing

Do you understand now?

**Comment by Xoui** [comment]
caap

**Pull request closed without merging**
