### PR TITLE
Implemented new alignment strategy

### PR DESCRIPTION
**Pull request by DerpmanDev**

### CODE REVIEW

**Comment by xbubbo** [comment]
# Issues
1. For me when I visited now.gg in localhost without the script at all it seems to display perfectly fine. (Not sure if this will happen for everyone though)
2. Doesn't properly adjust once you go in fullscreen
3. The control bar is in the middle of the screen
4. Constantly logs ``now.js:91 Uncaught TypeError: headers.remove is not a function
    at now.js:91:23``

**Comment by xbubbo** [comment]
> # Issues
> 1. For me when I visited now.gg in localhost without the script at all it seems to display perfectly fine. (Not sure if this will happen for everyone though)
> 2. Doesn't properly adjust once you go in fullscreen
> 3. The control bar is in the middle of the screen
> 4. Constantly logs `now.js:91 Uncaught TypeError: headers.remove is not a function at now.js:91:23`

@DerpmanDev let me know if/when you fix this.

**Comment by a4r5n** [comment]
i am a nigger

**Comment by xbubbo** [comment]
No response in two days, open another PR when you fix the issues above.

**Pull request closed without merging**
