### PR TITLE
Added Tony Hawk's Pro Skater 2,3 & 4

### PR DESCRIPTION
**Pull request by JoshMann15**

### CODE REVIEW

**Review by Bigfoot9999 — CHANGES_REQUESTED** [review]
I don't see where you added the files? Make sure to upload the game files to the games folder and then the rest looks good.

**Comment by JoshMann15** [comment]
look at the onclick bro

**Comment by JoshMann15** [comment]
onclick="go('https://browncha023.github.io/GBA/launcher.html#thps3')"

**Review by JoshMann15 — COMMENTED** [review]
look at the pull req and code for doom 1, 2

**Pull request merged**
