### PR TITLE
happy happy happy

### PR DESCRIPTION
**Pull request by airtag8892**
- fixed eagler
- added game

### CODE REVIEW

**Review by proudparrot2 — COMMENTED** [review]
Yes yes

**Review by proudparrot2 — APPROVED** [review]
Oh whoops

**Comment by proudparrot2** [comment]
Why isnt it working

**Comment by airtag8892** [comment]
nvm it worked when i was testing it on interstellar locally but not when deployed to something like hop.sh? idfk anymore 😭

**Comment by ShadowCoder100** [comment]
Hi render block me

**Comment by ShadowCoder100** [comment]
what do i do now

**Comment by ShadowCoder100** [comment]
idk how to deloy seen glitch don t work other deloy need credit card i am 13 not adult

**Comment by ShadowCoder100** [comment]
i don t have credit card other site don t work or other problem

**Comment by wyabubbo** [comment]
skull

**Pull request merged**
