### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by epeion-development**
Fixed Android

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
"Bug Fixes" *skids*

**Comment by BomberFish** [comment]
The state of GitHub PRs in the year of our lord two-thousand and twenty-four

**Comment by Riftriot** [comment]
This adds a lot to the software, makes it tremendously better, and fixes our longest standing issue.

**Comment by uhidontkno** [comment]
Ah yes, changing JSON files are "bug fixes".

**Comment by interpolation-0** [comment]
shocking quality
image
also he added his own arc integration

**Comment by uhidontkno** [comment]
> This adds a lot to the software, makes it tremendously better, and fixes our longest standing issue.

real

**Pull request closed without merging**
