### PR TITLE
NowGG Bypass Fix v2.

### PR DESCRIPTION
**Pull request by FlyawayBear**
Demo @ https://demo.decimals.link

Tested on; Discord, Reddit, Geforce Now (Semi tested), YouTube, TikTok, Google Images, PH (Tested by AirTag)

Compared to the last commit, all the following sites, and images + videos all work.

<3

Also updated Ultraviolet to the latest v1 version.

### CODE REVIEW

**Comment by airtag8892** [comment]
can confirm the last one on the list works, tested.

**Comment by tristandevs** [comment]
airtag

**Review by airtag8892 — APPROVED** [review]
i approve!

**Comment by impaxton** [comment]
can confirm, pornhub and horsecockxvideos works perfectly fine

**Comment by tristandevs** [comment]
hi guys

**Pull request closed without merging**
