### PR TITLE
Overhauled Navbar, added searchbar.

### PR DESCRIPTION
**Pull request by MadjikDotPng**
To fix TGT's awful design choices. Also could I have push access to the repo? Would be useful.

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
Make the search box so that it dynamically updates from iframe src. Also, the search box width is weird.

Lastly, make sure it's compatible with the (kinda shitty) Catppuccin themes (color on Mocha should be #1e1e2e)

**Comment by xbubbo** [comment]
> Make the search box so that it dynamically updates from iframe src. Also, the search box width is weird.
> 
> Lastly, make sure it's compatible with the (kinda shitty) Catppuccin themes (color on Mocha should be #1e1e2e)

It is compatible with the Catppuccin theme. 

I'm gonna adjust the navbar height and searchbox width tho

**Comment by IncognitoTGT** [comment]
Yeah the theming colors were weird last time

**Comment by IncognitoTGT** [comment]
it was looking weird on my personal laptop (with a larger screen)

**Pull request merged**
