### PR TITLE
delete more random images + changed all favicons to png

### PR DESCRIPTION
**Pull request by bruhwhyamisobad**
delete more random images and changed all favicons to png

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
who let bro cook
webp is better

**Comment by kxtzownsu** [comment]
fuck webp, svg on top

**Comment by Riftriot** [comment]
Hi yes can I get a performance killer burger with a side of useless assets added that aren't referenced anywhere in the code fries

**Comment by IncognitoTGT** [comment]
interstellar codebase?
more like impale my head codebase

**Pull request closed without merging**
