### PR TITLE
Suggestion to add Nav bar to tabs

### PR DESCRIPTION
**Pull request by Poodleschool**

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
In my opinion this is kinda dumb since it would fill up more space. Maybe edit so that it auto hides but this is kinda pointless.

**Comment by IncognitoTGT** [comment]
Bro went straight to the point

**Comment by Poodleschool** [comment]
> no.

At least a home button next to the tabs. Its inconvenient because you cant just hit back in about:blank

**Comment by IncognitoTGT** [comment]
True true but then what's wrong with just well......OPENING ANOTHER TAB WITH INTERSTELLAR IN ABOUT BLANK?
It's pointless.

**Comment by IncognitoTGT** [comment]
Also to add, you can just as easily add a home button to tabs too but that would make the tab bar look ugly as hell.

**Review by IncognitoTGT — APPROVED** [review]

**Comment by xbubbo** [comment]
fire 
image

**Pull request closed without merging**
