### PR TITLE
Half asleep, Sloppily done, Ui concept.

### PR DESCRIPTION
**Pull request by MadjikDotPng**
Not even gonna send an image. Just boot it up yourself and tell me if it's good or not. (It's not).

Took abt ~3 hours. Promotes a more clean UI and attempts to differentiate it from other web proxies.

### CODE REVIEW

**Comment by xbubbo** [comment]
I like the nav bar idea, but I feel like people aren't going to know what they are doing for the apps and tabs page.

The games and settings pages are obvious.

The searchbar looks really really weird though.

**Comment by IncognitoTGT** [comment]
I really, really like this idea. 
The only things I don't really like are the search bar (text too small), and the settings page is buggy. This should be something we could implement in V5. The UI would be better if the icons were updated. 

Search bar - use a similar shape and text size as Google.com
Settings - fix
Custom drop downs could also be something we can implement.

**Comment by MadjikDotPng** [comment]
Tooltips was an idea when I was implementing it but when I tried it ended up being extremely buggy. I think there's a way you could go about it that actually works though.

**Comment by MadjikDotPng** [comment]
Closing this PR due to the existence of a new design.

**Pull request closed without merging**
